### ISSUE TITLE
DP monitor no sound output

### ISSUE THREAD

**Issue by lofuxz** [webleon/Hackintosh-OptiPlex-7060-MFF#1]
Hi webleon
Thanks for your EFI sharing. I found there is no sound output via DP port.

**Comment by webleon** [comment]
HDMI/DP Sound output will cause various sleep/wake problems, so I simply disabled them by adding No-hda-gfx under DeviceProperties/Add/PciRoot(0x0)/Pci(0x1F,0x3). 

If you can fix sleep/wakeup issues by other ways, try to disable the No-hda-gfx settings, sound should come back.

**Comment by lofuxz** [comment]
Thanks webleon
