### ISSUE TITLE
测试没什么问题，但是重启 LOGO会花屏。然后卡在那里不动，必须要端开电源再开机才能正常进入

### ISSUE THREAD

**Issue by xuewei8829** [webleon/Hackintosh-OptiPlex-7060-MFF#2]

**Comment by webleon** [comment]
I‘ve never meet ur problem, but you can try as follows:

1. confirm the DVMT is 64M or larger
2. not using any signal adapter（hdmi/DVI/VGA）
3. change another DP cable

**Comment by SmartYou1995** [comment]
你好大佬，我的7060mmf使用的是dp转hdmi  可否在efi中帮忙注入dp转hdmi驱动？

**Comment by FlashTang** [comment]
@SmartYou1995  大佬说了，不要使用任何信号转接线
