### ISSUE TITLE
休眠唤醒后保持黑屏和突然黑屏的错误

### ISSUE THREAD

**Issue by xiaoyun-TaiChi** [webleon/Hackintosh-OptiPlex-7060-MFF#3]
测试出现休眠后唤醒黑屏无法继续操作和正常使用中的突然黑屏问题，4K显示器，DP直连。是否是个例

**Comment by hellosds** [comment]
7060mff+i5 8600t+AOC 4K显示器，DP直连，用了一阵子了，暂时没发现休眠后唤醒黑屏。
不过倒是HD630感觉有些时候，比如打开启动台、缩放窗口，卡顿明显啊。。。。不知道是不是核显驱动问题。

**Comment by xiaoyun-TaiChi** [comment]
7060mff + i5 8600t 同配置，目前出现上述问题，强制关机重启正常。频率较高，不知如何解决

**Comment by xiaoyun-TaiChi** [comment]
> 7060mff + i5 8600t + AOC 4K显示器，DP直连，用了一阵子了，暂时没发现休眠后唤醒黑屏。
> 不过倒是HD630感觉有些时候，可以打开启动台，缩放窗口，卡顿明显啊。。。。不知道是不是核显驱动问题。

可否查看一下对应的BIOS版本，我这面同步测试一下

**Comment by hellosds** [comment]
> > 7060mff + i5 8600t + AOC 4K显示器，DP直连，用了一阵子了，暂时没发现休眠后唤醒黑屏。
> > 不过倒是HD630感觉有些时候，可以打开启动台，缩放窗口，卡顿明显啊。。。。不知道是不是核显驱动问题。
> 
> 可否查看一下对应的BIOS版本，我这面同步测试一下

BIOS版本我升级到最新的1.8.0

**Comment by enquan** [comment]
遇到了相同的情况，只要睡眠超过一定时间，唤醒后屏幕就无法显示了，只能强制关机重启。显卡是HD630

**Comment by iwenbin** [comment]
7060mff + i5 8600t + Dell U2417h显示器1080p，DP直连，正常操作时会出现冻屏现象（鼠标键盘均无法操作），只能强制重启
