### ISSUE TITLE
请问 BCM94360CS2 你是怎么装上去的啊，空间不够啊

### ISSUE THREAD

**Issue by hellojinjie** [webleon/Hackintosh-OptiPlex-7060-MFF#5]
谢谢大佬提供的 EFI， 使用体验很棒，相当完美！

我和你一样买了一个 BCM94360CS2，用转接卡插上，但是卡的尺寸太大了啊，装不上去。即使将转接卡剪掉，BCM94360CS2 还是太长了，完全压不下去。
![黑苹果网卡](https://user-images.githubusercontent.com/204361/108809128-23962300-75e3-11eb-8c6f-03b86def5ad1.jpg)

**Comment by hellosds** [comment]
买反向转接卡试试。

**Comment by webleon** [comment]
我也是就这样架在音频口上面，没事的。

**Comment by hellojinjie** [comment]
> 我也是就这样架在音频口上面，没事的。

哈哈，那我找个东西给他固定一下，免得晃
