### ISSUE TITLE
大佬HDMI音频可以了请更新下AppleALC

### ISSUE THREAD

**Issue by jameslhc** [webleon/Hackintosh-OptiPlex-7060-MFF#6]
从其他地方下载尝试了下更新AppleALC版本就能实现HDMI音频，可以考虑处理下
咱们这个EFI里带的1.5.4的，好像1.5.6的就可以用了

另外是不是可以请你更新下大版本，更新到现在的OC0.7.7，这样是不是Monteney也可以在线更新了
谢谢

**Comment by charliecaiyu** [comment]
嗯，同求更新0.77，升级MONTEREY
